spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-atguigu-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-atguigu-test
  
#必须是utf-8
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/18856044233/microservicecloud-config.git
          default-branch: main